spring:
  application:
    name: currency-service
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      service:
        git:
          uri: file:///D:/Dev/Projects/SpringBoot/git
  
server:
  port: 8100
