spring:
  application:
    name: currency-conversion
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      service:
        git:
          uri: file:///D:/Dev/Projects/SpringBoot/git
  
server:
  port: 8100
  
eureka:
  client:
    serviceUrl: 
      defaultZone: http://localhost:8761/eureka
